---
name: geodash-plugin-overlays
controllers:
  - GeoDashControllerOverlays.js
directives:
  - geodashMapOverlays.js
templates:
  - map_overlays.tpl.html
less:
  - map_overlays.less
schemas:
  - map_overlays_schema.yml
